### ISSUE TITLE
请教一下, 弱类型的例子是?

### ISSUE THREAD

**Issue by nobodxbodon** [wkgcass/Latte-lang#1]
看着有点像动态类型检查的强类型啊?

**Comment by wkgcass** [comment]
首先强弱类型界定比较模糊。参考知乎这个问题 [弱类型、强类型、动态类型、静态类型语言的区别是什么？](https://www.zhihu.com/question/19918532)
应该说除去汇编，都会有类型这个概念吧
至于为啥我会说某些部分是弱类型呢＝ ＝
因为`LessTyping`的类型转换__可以__在运行时完成，并且依据不仅仅是原始类型和目标类型，还会考虑对象的状态（例如`lt.lang.Lang.castToBool`）
只不过设计时尽量限制了隐式类型转换，比如字面量不允许过分的转换（例如不允许`1 as bool`，但是`a=1 \n a as bool`就可以），再比如只有小部分情况会考虑对象状态，大部分还是只考虑类型。毕竟像某些语言的_字符串自动变成数字_有时候还是挺让人困扰的。

至于`LessTyping`的类型系统嘛，大概就是`groovy`的感觉吧。为了和java互通不得不提供静态类型，比如要重写方法就必须有方法签名。

--

至于怎么设计更加合理嘛。。希望能多多提出建议哦～
毕竟第一次设计语言，只能做出最适合我自己的，但是否最合理就得靠时间磨合并修改了 : )
